"""
schema.py — single contract for SettleTrace.

Every other module imports types from here. No business logic lives here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class MatchStatus(str, Enum):
    """High-level reconciliation outcome for a single order."""
    matched         = "matched"
    partial_hold    = "partial_hold"
    settlement_lag  = "settlement_lag"
    needs_review    = "needs_review"
    unresolved      = "unresolved"


class ExceptionReason(str, Enum):
    """Specific reason an order could not be fully matched."""
    fee_mismatch         = "fee_mismatch"
    gst_mismatch         = "gst_mismatch"
    refund_not_netted    = "refund_not_netted"
    duplicate_batch      = "duplicate_batch"
    missing_bank_credit  = "missing_bank_credit"
    orphan_bank_credit   = "orphan_bank_credit"
    currency_rounding    = "currency_rounding"
    settlement_lag       = "settlement_lag"      # credit arrived outside T+1/T+2 window
    partial_hold         = "partial_hold"        # Razorpay withheld 5-10% as reserve
    unknown              = "unknown"


# ---------------------------------------------------------------------------
# Core data models
# ---------------------------------------------------------------------------

@dataclass
class Order:
    """A single customer order captured from the Razorpay orders feed."""
    order_id:         str
    order_date:       str           # ISO-8601 date string, e.g. "2026-08-01"
    gross_amount:     float         # INR amount charged to the customer
    currency:         str  = "INR"
    refunded_amount:  float = 0.0


@dataclass
class SettlementLine:
    """One line from the Razorpay settlement report."""
    settlement_id:   str
    order_id:        str
    settled_date:    str            # ISO-8601 date string
    gross_amount:    float
    razorpay_fee:    float
    gst_on_fee:      float
    net_amount:      float          # gross_amount - razorpay_fee - gst_on_fee
    is_partial_hold: bool           = False
    hold_reason:     Optional[str]  = None


@dataclass
class BankCredit:
    """A credit entry as it appears on the bank statement."""
    credit_id:     str
    value_date:    str              # ISO-8601 date string
    utr:           str              # Unique Transaction Reference from NEFT/RTGS/IMPS
    amount:        float
    raw_narration: str = ""         # Full narration text from the bank file


@dataclass
class GLEntry:
    """A single line from the General Ledger export."""
    gl_id:       str
    entry_date:  str                # ISO-8601 date string
    account:     str                # Must be one of ACCOUNT_CATEGORIES
    amount_str:  str                # Raw string as exported (preserves sign & formatting)
    reference:   str = ""


@dataclass
class ReconciliationResult:
    """
    The output record produced for every order after the reconciliation pass.

    Fields
    ------
    order_id                 — links back to Order.order_id
    status                   — high-level MatchStatus
    matched_settlement_id    — SettlementLine.settlement_id that was paired, or None
    matched_bank_credit_id   — BankCredit.credit_id that was paired, or None
    expected_net             — what net_amount should be per the fee schedule
    actual_net               — net_amount from the settlement file
    delta                    — actual_net - expected_net  (0.0 when perfectly matched)
    exception_reason         — ExceptionReason if status != matched, else None
    llm_explanation          — free-text explanation generated by the LLM layer
    cited_rule               — which fee/policy rule the LLM referenced
    confidence               — model confidence score 0.0–1.0
    audit_trail              — ordered list of processing notes for full traceability
    """
    order_id:                str
    status:                  MatchStatus
    matched_settlement_id:   Optional[str]
    matched_bank_credit_id:  Optional[str]
    expected_net:            float
    actual_net:              float
    delta:                   float
    exception_reason:        Optional[ExceptionReason]
    llm_explanation:         str
    cited_rule:              str
    confidence:              float
    audit_trail:             List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Chart of accounts
# ---------------------------------------------------------------------------

ACCOUNT_CATEGORIES: List[str] = [
    "Sales Revenue",
    "Razorpay Fees",
    "GST on Fees (Input Credit)",
    "Refunds & Chargebacks",
    "Bank Charges",
    "Settlement Reserve (Held)",
    "Unreconciled Suspense",
]
